name: Run all tests

on:
  push:
    branches:
      - main

jobs:
  ###############################################
  # Matrix Definitions
  ###############################################
  create-test-matrix:
    runs-on: ubuntu-self-hosted
    timeout-minutes: 2
    outputs:
      matrix: ${{ steps.test-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - id: test-matrix
        run: echo "matrix=$(node scripts/testsEnabled.js)" >> $GITHUB_OUTPUT

  ###############################################
  # Open test run
  ###############################################
  open:
    runs-on: ubuntu-self-hosted
    timeout-minutes: 2
    outputs:
      test-run-id: ${{ steps.open-test-run.outputs.test-run-id }}
    steps:
      - run: echo "open a test run here"

      - id: open-test-run
        run: echo "test-run-id=123" >> $GITHUB_OUTPUT

  ###############################################
  # Run tests
  ###############################################
  test:
    needs:
      - open
      - create-test-matrix
    if: ${{ needs.create-test-matrix.outputs.matrix != '' }}
    strategy:
      matrix: ${{ fromJson(needs.create-test-matrix.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/playwright.yml
    with:
      brand: ${{ matrix.product.brand }}
      product: ${{ matrix.product.product }}
      suite: "all"

  ###############################################
  # Close test run
  ###############################################
  close:
    needs:
      - open
      - test
    runs-on: ubuntu-self-hosted
    timeout-minutes: 2
    if: ${{ always() }}
    steps:
      - run: echo "close a test run here"

      - run: echo "closing test run ${{ needs.open.outputs.test-run-id }}"
